import { Seeder, Factory } from 'typeorm-seeding';
import { Connection } from 'typeorm';
import VeiculoModelo from '../../modules/veiculos/entities/VeiculoModelo';

export default class VeiculosModelos implements Seeder {
  public async run(factory: Factory, connection: Connection): Promise<any> {
    await connection
      .createQueryBuilder()
      .insert()
      .into(VeiculoModelo)
      .values([
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 9,
          nome: 'GRANMINI',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 5,
          nome: 'Amarok',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 4,
          nome: 'Fox',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 4,
          nome: 'Fusca',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 4,
          nome: 'Gol',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 4,
          nome: 'Golf',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 4,
          nome: 'Jetta',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 4,
          nome: 'Kombi',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 4,
          nome: 'Parati',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 4,
          nome: 'Polo',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 4,
          nome: 'Santana',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 1,
          id_veiculo_especie: 4,
          nome: 'Voyage',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 2,
          id_veiculo_especie: 4,
          nome: 'Argo',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 2,
          id_veiculo_especie: 7,
          nome: 'Ducato',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 2,
          id_veiculo_especie: 7,
          nome: 'Elba',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 2,
          id_veiculo_especie: 7,
          nome: 'Fiorino',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 2,
          id_veiculo_especie: 4,
          nome: 'GranSiena',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 2,
          id_veiculo_especie: 4,
          nome: 'Mobi',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 2,
          id_veiculo_especie: 4,
          nome: 'Palio',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 2,
          id_veiculo_especie: 4,
          nome: 'Siena',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 2,
          id_veiculo_especie: 5,
          nome: 'Strada',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 2,
          id_veiculo_especie: 4,
          nome: 'Uno',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 4,
          nome: 'Astra',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 7,
          nome: 'Blazer',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 4,
          nome: 'Celta',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 4,
          nome: 'Colbat',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 4,
          nome: 'Corsa',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 7,
          nome: 'D20',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 7,
          nome: 'D40',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 4,
          nome: 'Meriva',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 4,
          nome: 'Onix',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 4,
          nome: 'Prisma',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 7,
          nome: 'Spin',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 5,
          nome: 'S10',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 3,
          id_veiculo_especie: 11,
          nome: 'Veraneio',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 4,
          id_veiculo_especie: 4,
          nome: 'EcoSport',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 4,
          id_veiculo_especie: 4,
          nome: 'Fiesta',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 4,
          id_veiculo_especie: 4,
          nome: 'Focus',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 4,
          id_veiculo_especie: 4,
          nome: 'Fusion',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 4,
          id_veiculo_especie: 4,
          nome: 'Ka',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 4,
          id_veiculo_especie: 7,
          nome: 'Pampa',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 4,
          id_veiculo_especie: 5,
          nome: 'F1000',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 4,
          id_veiculo_especie: 5,
          nome: 'F250',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 4,
          id_veiculo_especie: 5,
          nome: 'Ranger',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 5,
          id_veiculo_especie: 4,
          nome: 'Corolla',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 5,
          id_veiculo_especie: 4,
          nome: 'Etios',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 5,
          id_veiculo_especie: 5,
          nome: 'Hilux',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 5,
          id_veiculo_especie: 5,
          nome: 'Hilux SW4',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'CARGO 125CC',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 5,
          id_veiculo_especie: 5,
          nome: 'BANDEIRANTES',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'CARGO CB 600',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'CBX 200 STRADA',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'CBX 750 F INDY',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'NX 350 SAHARA',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'NX FALCON',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'NXR BROS 150',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'TITAN 125',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'TITAN KS 150',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'XLR 125CC',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 1,
          nome: 'XRE 300 CC',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 6,
          id_veiculo_especie: 4,
          nome: 'XRE 300 CC',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 8,
          id_veiculo_especie: 5,
          nome: 'Frontier',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 8,
          id_veiculo_especie: 11,
          nome: 'X Terra',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 9,
          id_veiculo_especie: 8,
          nome: 'BESTA 84CV',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 10,
          id_veiculo_especie: 6,
          nome: 'ATEGO 2430',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 10,
          id_veiculo_especie: 6,
          nome: 'STEELFORCE',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 10,
          id_veiculo_especie: 8,
          nome: 'SPRINTER',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 11,
          id_veiculo_especie: 11,
          nome: 'Boxer',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 13,
          id_veiculo_especie: 5,
          nome: 'L200',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 16,
          id_veiculo_especie: 4,
          nome: 'CLIO',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 16,
          id_veiculo_especie: 4,
          nome: 'Duster',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 16,
          id_veiculo_especie: 4,
          nome: 'Sandeiro',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 18,
          id_veiculo_especie: 1,
          nome: 'SPEED 150',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 20,
          id_veiculo_especie: 4,
          nome: 'Renegade',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 21,
          id_veiculo_especie: 4,
          nome: 'Buggy',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 22,
          id_veiculo_especie: 12,
          nome: 'TRATOR TL 75 EXITUS 4X2',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 23,
          id_veiculo_especie: 1,
          nome: 'XT 660R CC',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 23,
          id_veiculo_especie: 1,
          nome: 'XTZ 125',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 23,
          id_veiculo_especie: 1,
          nome: 'XTZ 150',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 23,
          id_veiculo_especie: 1,
          nome: 'XTZ 250',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 23,
          id_veiculo_especie: 1,
          nome: 'YBR 125',
          criado_por: '13444013',
        },
        {
          id_veiculo_marca: 24,
          id_veiculo_especie: 1,
          nome: 'TRAXX JH 125 G',
          criado_por: '13444013',
        },
        {
          nome: 'Outros',
          criado_por: '13444013',
        },
      ])
      .execute();
  }
}
