import { Seeder, Factory } from 'typeorm-seeding';
import { Connection } from 'typeorm';
import OrgaoEstado from '@modules/veiculos/entities/Orgao';

export default class OrgaosEstados implements Seeder {
  public async run(factory: Factory, connection: Connection): Promise<any> {
    await connection
      .createQueryBuilder()
      .insert()
      .into(OrgaoEstado)
      .values([
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Agência de Defesa Agropecuária do Ceará',
          sigla: 'ADAGRI',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Agência de Defesa Agropecuária do Ceará',
          sigla: 'ADAGRI',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'SECRETARIA DAS CIDADES',
          sigla: 'SCIDADES',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Departamento Estadual de Rodovias',
          sigla: 'DER',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Academia Estadual de Segurança Pública do Ceará',
          sigla: 'Aesp',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Agência Reguladora do Estado do Ceará',
          sigla: 'ARCE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Corpo de Bombeiros Militar do Estado do Ceará',
          sigla: 'CMBCE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Polícia Militar do Estado do Ceará',
          sigla: 'PMCE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Casa Civil ',
          sigla: 'CC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Ceasa',
          sigla: 'Ceasa',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Coordenadoria de Formação Docente e Educação a Distância',
          sigla: 'CED',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Companhia de Gás do Ceará',
          sigla: 'CEGAS',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Controladoria e Ouvidoria Geral do Estado ',
          sigla: 'CGE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Companhia de Desenvolvimento do Ceará',
          sigla: 'CODECE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Conselho de Políticas e Gestão do Meio Ambiente',
          sigla: 'CONPAM',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Departamento Estadual de Rodovias',
          sigla: 'DER',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Defensoria Pública do Estado do Ceará',
          sigla: 'DPG',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Empresa de Assistência Técnica e Extensão Rural do Ceará',
          sigla: 'EMATERCE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Empresa de Tecnologia da Informação do Ceará',
          sigla: 'ETICE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Fundação Ação Social',
          sigla: 'FAS',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome:
            'Fundação Cearense de Apoio ao Desenvolvimento Científico e Tecnológico. ',
          sigla: 'FUNCAP',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Fundação Universidade Estadual do Ceará',
          sigla: 'FUNECE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Gabinete do Governador',
          sigla: 'GABGOV',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Instituto do Desenvolvimento Agrário do Ceará',
          sigla: 'IDACE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: ' Instituto de Previdência do Estado do Ceara',
          sigla: 'IPEC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Instituto de Pesquisa e Estratégia Econômica do Ceará',
          sigla: 'IPECE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Instituto de Saúde dos Servidores do Estado do Ceará',
          sigla: 'ISSEC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Metrô de Fortaleza',
          sigla: 'METROFOR',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Organizações não Governamentais ',
          sigla: 'ONG',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Procuradoria-Geral do Estado do Ceará',
          sigla: 'PGE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria do Desenvolvimento Econômico',
          sigla: 'SDE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria do Desenvolvimento Agrário',
          sigla: 'SEAGRI',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria da Educação',
          sigla: 'SEDUC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria da Ciência, Tecnologia e Educação Superior',
          sigla: 'SECITECE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria da Fazenda',
          sigla: 'SEFAZ',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria da Agricultura, Pesca e Aquicultura',
          sigla: 'SEAPA',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria da Infraestrutura.',
          sigla: 'SEINFRA',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria da Justiça e Cidadania ',
          sigla: 'SEJUS',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria de Planejamento e Gestão',
          sigla: 'SEPLAG',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Serviço de Processamento de Dados do Estado do Ceará ',
          sigla: 'SEPROCE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria da Saúde do Ceará',
          sigla: 'SESA',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Sistema de Informações sobre Mortalidade',
          sigla: 'SIM',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria da Ouvidoria-Geral e do Meio Ambiente',
          sigla: 'SOMA',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria da Segurança Pública e Defesa Social',
          sigla: 'SSPDS',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Sistema Único de Previdência Social do Estado do Ceará',
          sigla: 'SUPSEC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Tribunal de Contas do Estado',
          sigla: 'TCE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Universidade Regional do Cariri',
          sigla: 'URCA',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Vice-Governadoria',
          sigla: 'VICEGOV',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Agência de Desenvolvimento do Estado do Ceará',
          sigla: 'ADECE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Assembleia Legislativa',
          sigla: 'AL',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Companhia de Água e Esgoto do Ceará',
          sigla: 'CAGECE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Companhia de Integração Portuária do Ceará',
          sigla: 'CEARAPORTOS',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Conselho Estadual de Educação',
          sigla: 'CEC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Conselho Estadual de Desenvolvimento Econômico',
          sigla: 'CEDE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome:
            'Controladoria Geral de Disciplina dos Órgãos de Segurança Pública e Sistema Penitenciário',
          sigla: 'CGD',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Companhia de Gestão dos Recursos Hídricos do Ceará',
          sigla: 'COGERH',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Documento de Arrecadação do Estado ',
          sigla: 'DAE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'DETRAN Departamento Estadual de Trânsito',
          sigla: 'DETRAN-CE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Escola de Gestão Pública do Estado',
          sigla: 'EGPE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Escola de Saúde Pública ',
          sigla: 'ESP',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Fundacao de Assistência Desportiva do Estado do Ceara',
          sigla: 'FADEC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Fundacao Estadual do Bem Estar do Menor do Ceara',
          sigla: 'FEBEMCE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Fundação Cearense de Meteorologia e Recursos Hídricos',
          sigla: 'FUNCEME',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Fundação de Teleducação do Ceará',
          sigla: 'FUNTELC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Governador',
          sigla: 'GOVERNADOR',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome:
            'Instituto de Desenvolvimento Institucional das Cidades do Ceará',
          sigla: 'IDECI',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Instituto de Pesquisa e Estratégia Econômica do Ceará ',
          sigla: 'IPECE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Instituto de Planejamento do Ceará ',
          sigla: 'IPLANCE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Junta Comercial do Estado do Ceará',
          sigla: 'JUCEC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Núcleo de Tecnologia e Qualidade Industrial do Ceará',
          sigla: 'NUTEC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Polícia Civil',
          sigla: 'PC',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Procuradoria Geral de Justiça ',
          sigla: 'PGJ',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria de Administração do Estado do Ceará',
          sigla: 'SEAD',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria da Cultura do Estado do Ceará',
          sigla: 'SECULT',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria Especial de Grandes Eventos Esportivos',
          sigla: 'SEGE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Superintendência Estadual do Meio Ambiente ',
          sigla: 'SEMACE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'SECRETARIA DO PLANEJAMENTO E COORDENAÇÃO',
          sigla: 'SEPLAN',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'SECRETARIA DO TRABALHO E AÇÃO SOCIAL',
          sigla: 'SETAS',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria do Turismo',
          sigla: 'SETUR',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Superintendência de Obras Hidráulicas',
          sigla: 'SOHIDRA',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria dos Recursos Hídricos',
          sigla: 'SERH',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Secretaria do Trabalho e Desenvolvimento Social',
          sigla: 'STDS',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Tribunal de Justiça',
          sigla: 'TJCE',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Estadual',
          unidade: 'CE',
          nome: 'Universidade Estadual Vale do Acaraú',
          sigla: 'UVA',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Federal',
          nome:
            'Instituto Brasileiro do Meio Ambiente e dos Recursos Naturais Renováveis',
          sigla: 'IBAMA',
          criado_por: '13444013',
        },
        {
          ente_federativo: 'Federal',
          nome: 'MINISTÉRIO DA JUSTIÇA',
          sigla: 'MJ',
          criado_por: '13444013',
        },
      ])
      .execute();
  }
}
